# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6a4cefe9f51995f4d5567ca1627ead1be26b85cfff6450e905709321c934da917afa9b70574427fad5144cf51a25a3bf7fa87ccc79f03cb3e36af03f4b11a0

test:
  secret_key_base: b32777ce4b30baf80014897c9ae81025e9b13dd07ab8c398a1a6487358d2e9775fe66c79abbcf0a509b34952ab96c128552b0792fa799607b06c6aa49a18f50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
